name: 'Merge Release PR'
description: 'Merges a release PR for a specific package'

inputs:
  package:
    description: 'Package name to merge release PR for'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  pr_merged:
    description: 'Whether the PR was successfully merged'
    value: ${{ steps.merge.outputs.pr_merged }}
  pr_number:
    description: 'The PR number that was merged'
    value: ${{ steps.merge.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - name: Merge release PR
      id: merge
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        PACKAGE="${{ inputs.package }}"
        echo "🔍 Looking for release PR for: $PACKAGE"
        
        # Find the release PR for this package
        PR_NUMBER=$(gh pr list --state open --json number,title | jq -r ".[] | select(.title | contains(\"release: @ui5/ $PACKAGE\")) | .number")
        
        if [[ -n "$PR_NUMBER" ]]; then
          echo "✅ Found PR #$PR_NUMBER for $PACKAGE"
          echo "🔄 Merging..."
          
          # Merge the PR
          gh pr merge $PR_NUMBER --squash
          
          echo "✅ Merged PR #$PR_NUMBER for $PACKAGE"
          echo "pr_merged=true" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        else
          echo "❌ No open release PR found for $PACKAGE"
          echo "pr_merged=false" >> $GITHUB_OUTPUT
          echo "pr_number=" >> $GITHUB_OUTPUT
        fi