name: 'Merge Release PR'
description: 'Find and merge a release PR for a specific package'
inputs:
  package:
    description: 'Package name to find and merge PR for'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
outputs:
  pr-number:
    description: 'PR number that was merged'
    value: ${{ steps.merge.outputs.pr-number }}
  merged:
    description: 'Whether a PR was found and merged'
    value: ${{ steps.merge.outputs.merged }}

runs:
  using: 'composite'
  steps:
    - name: Find and merge release PR
      id: merge
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        PACKAGE="${{ inputs.package }}"
        echo "🔍 Looking for release PR for: $PACKAGE"
        
        # Find release PR
        PR_NUMBER=$(gh pr list --state open --json number,title | jq -r '.[] | select(.title | startswith("release: @ui5/ '$PACKAGE' v")) | .number' | head -n1)
        
        if [[ -n "$PR_NUMBER" ]]; then
          echo "✅ Found PR #$PR_NUMBER for $PACKAGE"
          echo "🔄 Merging..."
          
          gh pr merge $PR_NUMBER --squash --admin
          
          echo "✅ Merged PR #$PR_NUMBER for $PACKAGE"
          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "merged=true" >> $GITHUB_OUTPUT
        else
          echo "❌ No release PR found for $PACKAGE"
          echo "merged=false" >> $GITHUB_OUTPUT
        fi