name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: General checks and tests
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Perform ESLint check
      run: npm run lint

    # TODO: Enable when "cli" package has been integrated into monorepo
    # - name: Perform Licenses check
    #   run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Run unit tests
      run: npm run coverage

    - name: Generate JSDoc documentation
      run: npm run jsdoc-generate

    - name: Generate merged JSON schema
      run: npm run schema-generate

    - name: Generate CLI documentation
      run: npm run generate-cli-doc
